# Generated by Django 2.1.2 on 2023-06-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_warden',
            field=models.BooleanField(default=False),
        ),
    ]
